apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: fluentd
  name: fluentd
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fluentd
    spec:
      containers:
      - image: regoo707/fluentd:latest
        name: fluentd
        ports:
        - containerPort: 24224
        - containerPort: 24224
          protocol: UDP
        resources: {}
      restartPolicy: Always
status: {}
